### ISSUE TITLE
The strings which consist of consonants.

### ISSUE THREAD

**Issue by KimYounghoo** [m0ai/charming-slack-bot#1]
```
정답:ㅊㅅㅋㅈ:게임 # I mean... '초성퀴즈', a mistake..
정답:초성퀴즈:게임 # ok this is correct one!

prob
게임: ㅊㅅㅋㅈ
!초성퀴즈
응 아니야
!ㅊㅅㅋㅈ
... 정답! ... # ?
```
This bug causes confusions :(

I think we can handle this when the given strings are processed, or you can also solve this by enabling examiners to adjust/control the quizzes they submitted.

**Comment by m0ai** [comment]
Yes, we can handle this thing you mentioned. we know that both methods you said are great for this process, so we will apply soon. or expect your contribution :p

**Comment by m0ai** [comment]
```python
if list(set(CHOSUNG_LIST)&set(splitKeywordList)) != list():
    return None
 ```
[The modification is complete.](https://github.com/m0ai/charming-slack-bot/commit/4ada9c83489fdee6c528ca800ca982264edb86e4)
we are check if includes a consist of consonants in the user input value.
Additionally, enabling examiners to control quizzes is not scheduled yet.
